# Generated by Django 2.0.13 on 2019-10-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191022_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawling',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
