# Generated by Django 2.0.13 on 2019-11-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='google',
            name='text',
        ),
    ]
