# Generated by Django 2.0.13 on 2019-11-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191105_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
