# Generated by Django 2.0.13 on 2019-11-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_search_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='google',
            old_name='title',
            new_name='search_title',
        ),
    ]
