# Generated by Django 2.0.13 on 2019-11-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191105_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='title',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
