# Generated by Django 2.0.13 on 2019-11-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_google_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(verbose_name='IS customer')),
                ('is_seller', models.BooleanField(verbose_name='IS DOCTOR')),
            ],
        ),
    ]
