# Generated by Django 2.0.13 on 2019-11-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=10),
        ),
    ]
