# Generated by Django 2.0.13 on 2019-11-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191110_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('h', '지난 1시간'), ('m', '지난 1개\x1d월'), ('y', '지난 1년'), ('w', '지난 1주'), ('d', '지난 1일'), ('t', '모든날짜')], default='t', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('h', '지난 1시간'), ('m', '지난 1개\x1d월'), ('y', '지난 1년'), ('admin', '지난 1주'), ('d', '지난 1일'), ('user', '모든날짜')], default='user', max_length=10),
        ),
    ]
