# Generated by Django 2.0.13 on 2019-11-11 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191111_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='published_date',
        ),
        migrations.AddField(
            model_name='search',
            name='searched_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('d', '지난 1일'), ('admin', '지난 1주'), ('y', '지난 1년'), ('m', '지난 1개\x1d월'), ('user', '모든날짜'), ('h', '지난 1시간')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('d', '지난 1일'), ('t', '모든날짜'), ('y', '지난 1년'), ('m', '지난 1개\x1d월'), ('w', '지난 1주'), ('h', '지난 1시간')], default='t', max_length=10),
        ),
    ]
