# Generated by Django 2.0.13 on 2019-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191111_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='searched_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='search',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('admin', '지난 1주'), ('h', '지난 1시간'), ('d', '지난 1일'), ('m', '지난 1개\x1d월'), ('y', '지난 1년'), ('user', '모든날짜')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('h', '지난 1시간'), ('d', '지난 1일'), ('m', '지난 1개\x1d월'), ('t', '모든날짜'), ('y', '지난 1년'), ('w', '지난 1주')], default='t', max_length=10),
        ),
    ]
