# Generated by Django 2.0.13 on 2019-11-11 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20191111_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('d', '지난 1일'), ('user', '모든날짜'), ('h', '지난 1시간'), ('y', '지난 1년'), ('admin', '지난 1주'), ('m', '지난 1개\x1d월')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('t', '모든날짜'), ('d', '지난 1일'), ('h', '지난 1시간'), ('y', '지난 1년'), ('w', '지난 1주'), ('m', '지난 1개\x1d월')], default='t', max_length=10),
        ),
        migrations.AddField(
            model_name='searchcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchcomments', to='blog.Search'),
        ),
    ]
