# Generated by Django 2.0.13 on 2019-11-12 00:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191112_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCommentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchcommentsdetails', to='blog.SearchComment')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('d', '지난 1일'), ('admin', '지난 1주'), ('y', '지난 1년'), ('h', '지난 1시간'), ('user', '모든날짜'), ('m', '지난 1개\x1d월')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('w', '지난 1주'), ('d', '지난 1일'), ('y', '지난 1년'), ('h', '지난 1시간'), ('t', '모든날짜'), ('m', '지난 1개\x1d월')], default='t', max_length=10),
        ),
    ]
