# Generated by Django 2.0.13 on 2019-11-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191112_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('y', '지난 1년'), ('m', '지난 1개\x1d월'), ('h', '지난 1시간'), ('user', '모든날짜'), ('d', '지난 1일'), ('admin', '지난 1주')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('y', '지난 1년'), ('m', '지난 1개\x1d월'), ('h', '지난 1시간'), ('w', '지난 1주'), ('t', '모든날짜'), ('d', '지난 1일')], default='t', max_length=10),
        ),
    ]
