# Generated by Django 2.0.13 on 2019-11-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191112_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('d', '지난 1일'), ('m', '지난 1개\x1d월'), ('y', '지난 1년'), ('user', '모든날짜'), ('admin', '지난 1주'), ('h', '지난 1시간')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('d9', '매일 9시'), ('w9', '매주 9시'), ('m', '지난 1개\x1d월'), ('w', '지난 1주'), ('t', '모든날짜'), ('y', '지난 1년'), ('d', '지난 1일'), ('h', '지난 1시간')], default='t', max_length=10),
        ),
    ]
