# Generated by Django 2.0.13 on 2019-11-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20191119_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('admin', '지난 1주'), ('y', '지난 1년'), ('m', '지난 1개\x1d월'), ('user', '모든날짜'), ('d', '지난 1일'), ('h', '지난 1시간')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('w9', '매주 9시'), ('y', '지난 1년'), ('m', '지난 1개\x1d월'), ('d', '지난 1일'), ('t', '모든날짜'), ('h', '지난 1시간'), ('w', '지난 1주'), ('d9', '매일 9시')], default='t', max_length=10),
        ),
    ]
