# Generated by Django 2.0.13 on 2019-11-25 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20191125_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('h', '지난 1시간'), ('y', '지난 1년'), ('admin', '지난 1주'), ('m', '지난 1개\x1d월'), ('user', '모든날짜'), ('d', '지난 1일')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('d9', '매일 9시'), ('h', '지난 1시간'), ('y', '지난 1년'), ('w9', '매주 9시'), ('t', '모든날짜'), ('w', '지난 1주'), ('m', '지난 1개\x1d월'), ('d', '지난 1일')], default='t', max_length=10),
        ),
    ]
