# Generated by Django 2.0.13 on 2019-11-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20191125_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryone',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searchceleryone', to='blog.Search'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('m', '지난 1개\x1d월'), ('d', '지난 1일'), ('admin', '지난 1주'), ('user', '모든날짜'), ('y', '지난 1년'), ('h', '지난 1시간')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('m', '지난 1개\x1d월'), ('d9', '매일 9시'), ('d', '지난 1일'), ('t', '모든날짜'), ('w9', '매주 9시'), ('w', '지난 1주'), ('y', '지난 1년'), ('h', '지난 1시간')], default='t', max_length=10),
        ),
    ]
