# Generated by Django 2.0.13 on 2019-11-26 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20191126_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('user', '모든날짜'), ('m', '지난 1개\x1d월'), ('h', '지난 1시간'), ('d', '지난 1일'), ('admin', '지난 1주'), ('y', '지난 1년')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='period',
            field=models.CharField(choices=[('m', '지난 1개\x1d월'), ('d9', '매일 9시'), ('h', '지난 1시간'), ('w9', '매주 9시'), ('d', '지난 1일'), ('t', '모든날짜'), ('y', '지난 1년'), ('w', '지난 1주')], default='t', max_length=10),
        ),
        migrations.AddField(
            model_name='celerytwo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searchcelerytwo', to='blog.Search'),
        ),
    ]
